services:
  # API Service
  - type: web
    name: real-estate-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
      - key: API_DATA_ENABLED
        value: true
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT
      - key: DASHBOARD_URL
        value: https://real-estate-dashboard.onrender.com
    autoDeploy: true

  # Dashboard Service
  - type: web
    name: real-estate-dashboard
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
      - key: API_URL
        value: https://real-estate-api.onrender.com
    autoDeploy: true

# Database
databases:
  - name: real-estate-db
    databaseName: real_estate_db
    user: real_estate_user
    plan: starter
    postgresMajorVersion: 15
    ipAllowList: [] # Allow all IPs
    postDeploy: bash scripts/init_render.sh